### ISSUE TITLE
No outwall.txt anymore?

### ISSUE THREAD

**Issue by debiansid** [x1angli/regional-ip-addresses#1]
Why there is no outwall.txt in output dir anymore?

Thanks

**Comment by x1angli** [comment]
@debiansid 
sorry about that. I've been busy w/ other stuff recently, so when I refactored the code last time, I forgot to refactor the module/ func that generates `outwall.txt`.

But, the thing is, i've already checked in [ipaddr_util.py](https://github.com/x1angli/regional-ip-addresses/blob/master/ipaddr_util.py), and you could look into it to write your own code that generates outwall.txt. Further, you would be more than appreciated if you can submit a pull request. 😃

**Comment by debiansid** [comment]
i just checkout c116403 to generate outwall.txt. because I dont know anything about coding.
thanks

**Comment by x1angli** [comment]
> i just checkout [c116403](https://github.com/x1angli/regional-ip-addresses/commit/c1164033500eb6a9205b35456478418bff03f133) to generate outwall.txt. because I dont know anything about coding.

Dear friend @debiansid 
May I ask why you need the list of overseas IP addresses? 

Although this python repo is simple and naive, it's just a component of a larger plan rather than a standalone tool. Besides,  this repo intended for advanced users only, which means I expect end-users learn how to configure IP table rules .  

That is to say, even if the requested outwall.txt is provided (either manually or programmatically)  to you, you can do very little stuff with it.  That's why I am strongly interested.....

**Comment by debiansid** [comment]
I need outwall.txt in my ss-local as its acl to proxy all outside China IP address. Does it make any sense  to you?

**Comment by x1angli** [comment]
> I need outwall.txt in my ss-local as its acl to proxy all outside China IP address. Does it make any sense to you?

do you need just ipv4? or both v4 and v6?

**Comment by x1angli** [comment]
@debiansid 

problem resolved in 637950690374e6554d40ccb2666da19b186c0dd4

https://github.com/x1angli/regional-ip-addresses/blob/master/output/out-CN-ipv4.txt
https://github.com/x1angli/regional-ip-addresses/blob/master/output/out-CN-ipv6.txt

it should work. let me know if you have further questions

closing this ticket
